name: MyDuksCI
on: 
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  rspec:
    runs_on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - user: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - run: cd api && bundle install
